print('naaminvoer')
name = input('geef jouw naam ')
adres = input('geef jouw adres ')
postcode = input('geef jouw postcode ')
woonplaats = input('geef jouw woonplaats ')
print (" ----------------------------------------------------")
print ('|  Naam      :  '   + name  )           
print ('|  Adres     :  '   + adres )         
print ('|  Postcode  :  '   + postcode)                      
print ('|  Woonplaats:  '   + woonplaats)                   
print (" ----------------------------------------------------")
