pp = float(7.45)
seat = float(0.37)
tijd = float(9)
allemaal = float(4)
voltijd = float(3.33)
personen = float(29.8)
stoelprijs = float(13.32)
duur = float(45)
totaalprijs = float(43.12)
print (seat * tijd)
print (voltijd * allemaal)
print (pp * allemaal)
print (personen + stoelprijs)
print ("dit geweldige dagje uit met " + str(allemaal) + " mensen in de speelhal met " + str(duur) + " minuten VR kost je maar " + str(totaalprijs) + " euro")

